<?php ?>
<input type="button" name="reload_button" id="reload_button" value="Reload Page">

<script type="text/javascript">
    (function () {
        require(["jquery"], function ($) {
            $(document).ready(function ($) {
                $("#reload_button").on("click", function (e) {
                    location.reload();
                })
            });
        });
    })();
</script>

